ALTER TABLE `Assessment` ADD COLUMN `relationship` ENUM('PARENT', 'GUARDIAN', 'TEACHER', 'CHILDCARE_PROVIDER', 'GRANDPARENT', 'FOSTER_PARENT', 'OTHER') NULL;

ALTER TABLE `User` ADD COLUMN `firstName` VARCHAR(191) NULL;
ALTER TABLE `User` ADD COLUMN `middleName` VARCHAR(191) NULL;
ALTER TABLE `User` ADD COLUMN `lastName` VARCHAR(191) NULL;
ALTER TABLE `User` ADD COLUMN `phone` VARCHAR(191) NULL;
ALTER TABLE `User` ADD COLUMN `address` TEXT NULL;

ALTER TABLE `Child` ADD COLUMN `firstName` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Child` ADD COLUMN `middleName` VARCHAR(191) NULL;
ALTER TABLE `Child` ADD COLUMN `lastName` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `Child` ADD COLUMN `registrationNumber` VARCHAR(191) NULL;

UPDATE `Child` SET `firstName` = SUBSTRING_INDEX(`fullName`, ' ', -1), `lastName` = SUBSTRING_INDEX(`fullName`, ' ', 1) WHERE `fullName` IS NOT NULL AND `fullName` != '';

ALTER TABLE `Assessment` ADD COLUMN `completionDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE `Assessment` ADD COLUMN `evaluatorFirstName` VARCHAR(191) NULL;
ALTER TABLE `Assessment` ADD COLUMN `evaluatorMiddleName` VARCHAR(191) NULL;
ALTER TABLE `Assessment` ADD COLUMN `evaluatorLastName` VARCHAR(191) NULL;
ALTER TABLE `Assessment` ADD COLUMN `evaluatorAddress` TEXT NULL;
ALTER TABLE `Assessment` ADD COLUMN `evaluatorHomePhone` VARCHAR(191) NULL;
ALTER TABLE `Assessment` ADD COLUMN `evaluatorOtherPhone` VARCHAR(191) NULL;
ALTER TABLE `Assessment` ADD COLUMN `evaluatorEmail` VARCHAR(191) NULL;
ALTER TABLE `Assessment` ADD COLUMN `helperName` VARCHAR(191) NULL;
ALTER TABLE `Assessment` ADD COLUMN `programRegistrationNumber` VARCHAR(191) NULL;
ALTER TABLE `Assessment` ADD COLUMN `programName` VARCHAR(191) NULL;

